- name: Install tools via apt
  apt:
    pkg:
      - python3-pyserial

- name: Create a directory for the octopi service
  ansible.builtin.file:
    path: /opt/octopi
    state: directory

- name: Copy Files which are defining the service
  ansible.builtin.file:
    path: "/opt/octopi/{{item}}"
    state: directory
  loop:
    - octoprint
    - spoolman
    - autorestic
    - autorestic/cron

- name: Templating Environment
  ansible.builtin.template:
    src: env.j2
    dest: /opt/octopi/.env

- name: Copy cron definition
  ansible.builtin.copy:
    src: cron
    dest: /opt/octopi/autorestic/

- name: Template Autorestic Config
  ansible.builtin.template:
    src: config.yml.j2
    dest: /opt/octopi/autorestic/config.yml


- name: Copy docker-compose.yml to target host
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/octopi/docker-compose.yml
  register: docker_compose_yaml

- name: Start the octopi service with Docker Compose
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /opt/octopi

- name: Pull on change
  when: docker_compose_yaml.changed
  command:
    chdir: /opt/octopi
    cmd: docker compose pull

- name: Restart on change
  when: docker_compose_yaml.changed
  command:
    chdir: /opt/octopi
    cmd: docker compose restart
